# Setup
title:            Harry James Moss
tagline:          'Personal site'
description:      'Research Software Engineer at the British Library'
url:              http://harryjmoss.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Harry James Moss'
  url:            https://twitter.com/invariantmoss

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist